<div class="container">
            <h1 class="heading">Please log in</h1>
            <?php if(isset($data['errors']) && is_array($data['errors'])):
                foreach($data['errors'] as $error): ?>
                    <p class="text-danger text-center"><?php echo $error ?></p>
                <?php endforeach;
            endif; ?>
            <form action="/index/auth/" method="post" class="login-form">
                <div class="form-group">
                    <label for="userName">Write your Name</label>
                    <input type="text" name="userName" required>
                </div>

                <div class="form-group">
                    <label for="userPassword">Write your password</label>
                    <input type="password" name="userPassword" required>
                </div>
                <input type="submit" class="button" value="Log in">
            </form>
</div>
